version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predictive_maintenance_api
    command: bash -c "python src/data_simulation.py && python src/train.py && uvicorn api.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predictive_maintenance_streamlit
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - api
    volumes:
      - ./:/app
